# Generated by Django 5.0.4 on 2024-04-20 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100, verbose_name='Machine Name')),
                ('machine_serial_no', models.CharField(max_length=100, unique=True, verbose_name='Machine Serial Number')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.CharField(max_length=100, verbose_name='Cycle Number')),
                ('unique_id', models.CharField(max_length=100, unique=True, verbose_name='Unique Identifier')),
                ('material_name', models.CharField(max_length=100, verbose_name='Material Name')),
                ('start_time', models.DateTimeField(verbose_name='Start Time of Production')),
                ('end_time', models.DateTimeField(verbose_name='End Time of Production')),
                ('duration', models.FloatField(verbose_name='Duration of Production (hours)')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oee_app.machines', verbose_name='Machine')),
            ],
        ),
    ]
